# EXPORTS
export SCALA_HOME="/Users/enzhao/suanec/libs/scala-2.11.8"
export SBT_HOME="/Users/enzhao/suanec/libs/sbt-0.13.15"
export HADOOP_HOME=/Users/enzhao/suanec/libs/hadoop-2.7.3
export SPARK_HOME=/Users/enzhao/suanec/libs/spark-2.0.2-bin-hadoop2.7
export PATH=$PATH:$SCALA_HOME/bin:$HADOOP_HOME/bin:$HADOOP_HOME/sbin:$SPARK_HOME/bin:$SPARK_HOME/sbin:$SBT_HOME/bin:
export ENV_HOME=/Users/enzhao/suanec/libs/envs



# ALIAS
alias suanec="sh $ENV_HOME/suanec@175.sh"
alias root175="sh $ENV_HOME/Zroot@175.sh"
alias hadoop175="sh $ENV_HOME/hadoop@175.sh"
alias root176="sh $ENV_HOME/Zroot@176.sh"
alias hadoop176="sh $ENV_HOME/hadoop@176.sh"
alias suanecg="sh $ENV_HOME/g-channel.sh"
alias suaneclt="sh $ENV_HOME/LT1-channel.sh"
alias suaneclt2="sh $ENV_HOME/LT2-channel.sh"
alias suanecdx="sh $ENV_HOME/DX1-channel.sh"
alias suanecdx2="sh $ENV_HOME/DX2-channel.sh"

# Linux Alias
alias ll="ls -ltah"
alias lsz='ls -lSah'
alias wsp="cd ~/suanec/ksp"
alias ckd="cd ~/suanec/ksp/dataflow"
alias ecp="cp -rvfp"
alias ldir='ls -lh|grep ^d'
alias h5='head -5'
alias h1='head -1'
alias jj="jobs -l"
alias tf="tail -f"
alias lduh='du --max-depth=1 -h'
alias rmr="rm -rvf"


# git ALIASES
alias ga="git add"
alias gs="git status"
alias gc="git commit"
alias gp="git push"
alias gpp="git pull"
alias gclone="git clone"
alias ginit="git init"
alias gadd="git add"
alias gmv="git mv"
alias greset="git reset"
alias grm="git rm"
alias gbisect="git bisect"
alias ggrep="git grep"
alias glog="git log"
alias gshow="git show"
alias gstatus="git status"
alias gbranch="git branch"
alias gcheckout="git checkout"
alias gcommit="git commit"
alias gdiff="git diff"
alias gmerge="git merge"
alias grebase="git rebase"
alias gtag="git tag"
alias gfetch="git fetch"
alias gpull="git pull"
alias gpush="git push"


# added by Anaconda2 4.4.0 installer
export PATH="/Users/enzhao/suanec/libs/anaconda2/bin:$PATH"
